# Generated by Django 2.1.2 on 2018-12-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('scale', models.CharField(choices=[('ug', 'Undergraduate Scale (4.0-0.7)'), ('gr', 'Graduate Scale (4.0-1.7)')], max_length=5)),
                ('scheme', models.TextField()),
                ('created_by', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('provisioned_date', models.DateTimeField(null=True)),
                ('is_deleted', models.NullBooleanField()),
                ('deleted_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradingStandardCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=80)),
                ('grading_standard_id', models.CharField(max_length=30, null=True)),
                ('provisioned_date', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_standard.GradingStandard')),
            ],
        ),
    ]
