language: python
python:
  - "2.7"
install:
  - pip install .
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - npm install jshint
  - cp travis-ci/manage.py manage.py
script:
  - pep8 grading_standard/
  - jshint grading_standard/static/grading_standard/js/standard.js --verbose
  - coverage run --source=grading_standard manage.py test grading_standard
after_script:
  - coveralls
notifications:
