sudo: required
language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - RELEASE_NAME="grading-standards"
  - DJANGO_APP="grading_standard"
  - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
  - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
  - DEPLOY_SCRIPT=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master/travis-ci/deploy.sh
  - GCP_JSON_KEY=gcp.json
  - secure: gH2GoEnfD8MEGw7ANunf8fc9bmemsWl5Rr2kOf1rkj/yGjNcJLifcy12qvMMwnq9phsA5VuDjUS9BH5kA/4SLLblO6X4kMxTzMCSpQeqhs41IuXx2tfz7R7d160GoElSbWwR0qHw+BDuNqxaL/cBQXJi+uKn8B7XbcYPsox4olbIjG56txxkREEUWGyrJPonJNdfodmVGac2MV3q6xry0SN+1UXvpYVK8+LtXUNdP6xJiPeC1J26upONet6Sj6SRjsYIpfLqwW7A57UfqIsmWK3yiqjv+PqDXvUktiGXxhOCIpBH4lSOHenHmU58iHGul/d0UJxUoFA4K4iO+1GnBZOv/RwbrYmgEz3+yPki4udWlI2VjUaYJvDZV9u23bQRs4pFFa91p0Df6bRV176XpnPGyGH4EIc125lf6XHc8r8IVgSQV4XwNa5DqqgzyWZTj/QgPAhhT/AP5DZjH31nrmUDoq/7u3FmeK2cVS+Xzi5gb1irkT01iMk94SxJ7a3llhBxvZP8sXexeYxsbprFxIUPH7y/xUwXuV5pbmKlu8LthdN/1tSZdWJC1ZxkuIkPqL3v1vgpzwV5GcYRd+pqqhwZshzHQuZsAimQ/WQGqLYT47U7zRgpFoINgzseVOCGCsjcN8bnLHjcOSro8ZrBnuLCYPp2jmUTB/HliTNBg/0=
install:
- docker build --target app-container -t "$IMAGE_TAG" .
- docker build -t app-test-container .
before_script:
- pip install coverage
- pip install coveralls
script:
- docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev"
  -e "AUTH=BLTI_DEV" app-test-container bash -c ". ./travis-ci/test.sh"
after_success:
- cp /tmp/.coverage.* .
- coverage combine
- coveralls
- openssl aes-256-cbc -K $encrypted_0e718fcdeb51_key -iv $encrypted_0e718fcdeb51_iv
  -in gcp.json.enc -out gcp.json -d
deploy:
- provider: script
  skip_cleanup: true
  script: curl -Ls "$DEPLOY_SCRIPT" | bash
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH =~ ^(master|develop)$
