version: '2'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: BLTI_DEV
      LTI_DEVELOP_APP: grading_standard
    restart: always
    container_name: app-grading-standard
    build:
      context: .
    volumes:
      - ./grading_standard:/app/grading_standard
    ports:
      - "8000:8000"
