resources:
  limits:
    cpu: "500m"
    memory: "1.0Gi"
  requests:
    cpu: "50m"
    memory: "256Mi"

ingress:
  enabled: false
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
externalService:
  enabled: true
  name: grading-standards-mysql-service
  type: ClusterIP
  serviceAddress: 172.18.0.28
  servicePort: 3306
database:
  engine: mysql
  name: grading_standards_test
  hostname: grading-standards-mysql-service
  secretName: db-grading-standards.canvas.uw.edu-sql-secrets
repo: grading-standards
instance: db
memcached:
  enabled: false
certs:
  mounted: false
environmentVariables:
  - name: CLUSTER_CNAME
    value: db-grading-standards.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: test
  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "10"
externalSecrets:
  enabled: true
  secrets:
    - name: db-grading-standards.canvas.uw.edu-secrets
      externalKey: grading-standards/test/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: db-grading-standards.canvas.uw.edu-shared-secrets
      externalKey: grading-standards/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
        - name: documentation-url
          property: documentation-url
    - name: db-grading-standards.canvas.uw.edu-canvas-secrets
      externalKey: canvas/shared/secrets
      data:
        - name: canvas-api-token
          property: canvas-api-token
    - name: db-grading-standards.canvas.uw.edu-sql-secrets
      externalKey: canvas/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: db-grading-standards.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: db-grading-standards.canvas.uw.edu-shared-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: db-grading-standards.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: db-grading-standards.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-iv
  documentationURL:
    name: DOCUMENTATION_URL
    secretName: db-grading-standards.canvas.uw.edu-shared-secrets
    secretKey: documentation-url
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: db-grading-standards.canvas.uw.edu-canvas-secrets
    secretKey: canvas-api-token
