autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
affinity:
   podsSpanNodes: true

ingress:
  enabled: true
  tls:
    grading-standards:
      secretName: grading-standards.canvas.uw.edu-ingress-cert
      hosts:
        - grading-standards.canvas.uw.edu
  hosts:
    grading-standards:
      host: grading-standards.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true

externalService:
  enabled: true
  name: grading-standards-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.28
  servicePort: 3306
database:
  engine: mysql
  name: grading_standards_prod
  hostname: grading-standards-db-service
  secretName: grading-standards.canvas.uw.edu-sql-secrets

repo: grading-standards
instance: prod
image:
  repository: gcr.io/uwit-mci-axdd/grading-standards
  tag: IMAGE_TAG

memcached:
  enabled: false

certs:
  mounted: false

environmentVariables:
  - name: CLUSTER_CNAME
    value: grading-standards.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: prod
  - name: CANVAS_ENV
    value: PROD
  - name: CANVAS_TIMEOUT
    value: "10"

externalSecrets:
  enabled: true
  secrets:
    - name: grading-standards.canvas.uw.edu-secrets
      externalKey: axdd/kv/data/grading-standards/prod/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: grading-standards.canvas.uw.edu-shared-secrets
      externalKey: axdd/kv/data/grading-standards/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
        - name: documentation-url
          property: documentation-url
    - name: grading-standards.canvas.uw.edu-canvas-secrets
      externalKey: axdd/kv/data/canvas/shared/secrets
      data:
        - name: canvas-api-token
          property: canvas-api-token
    - name: grading-standards.canvas.uw.edu-sql-secrets
      externalKey: axdd/kv/data/canvas/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: grading-standards.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: grading-standards.canvas.uw.edu-shared-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: grading-standards.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: grading-standards.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-iv
  documentationURL:
    name: DOCUMENTATION_URL
    secretName: grading-standards.canvas.uw.edu-shared-secrets
    secretKey: documentation-url
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: grading-standards.canvas.uw.edu-canvas-secrets
    secretKey: canvas-api-token
